baseURL: https://giovanniaguirre.me/
languageCode: en-us
title: Giovanni Aguirre

menu:
  main:
  - identifier: home
    title: Giovanni Aguirre
    url: /
    weight: 1
  - identifier: blog
    title: Blog
    url: /blog/
    weight: 2
  - identifier: contact
    title: Contact
    url: /contact/
    weight: 2
