
services:
  website-nginx:
    build:
      context: ../
      dockerfile: ./docker.production/website-nginx.dockerfile
    image: giobyte/website-nginx:1.0
    container_name: website-nginx
    ports:
      - "8080:80"